CREATE SEQUENCE SEQ_STUDENT_NO;

CREATE TABLE STUDENT(
	STUDENT_NO NUMBER DEFAULT SEQ_STUDENT_NO.NEXTVAL CONSTRAINT PK_STUDENT_NO PRIMARY KEY,
	STUDENT_NAME VARCHAR2(20) CONSTRAINT NN_STUDENT_NAME NOT NULL,
	AGE NUMBER,
	GENDER CHAR(1) CONSTRAINT CK_STUDENT_GENDER CHECK(GENDER IN('M','F')),
	GRADE NUMBER CONSTRAINT CK_STUDENT_GRAE CHECK(GRADE IN('1','2','3')),
	MAJOR VARCHAR2(50),
	EMAIL VARCHAR2(50)
);

SELECT * FROM student;